name: fvm
description: A simple cli to manage Flutter SDK versions per project. Support
  channels, releases, and local cache for fast switching between versions.
version: 2.4.1
homepage: https://github.com/leoafarias/fvm

environment:
  sdk: ">=2.19.0 <3.0.0"

executables:
  fvm: fvm
  flutter-select: flutter_select

dependencies:
  args: ^2.4.2
  # cli_config: ^0.1.1
  date_format: ^2.0.7
  git: ^2.2.1
  interact: ^2.2.0
  io: ^1.0.4
  mason_logger: ^0.2.8
  meta: ^1.9.1
  path: ^1.8.3
  pub_semver: ^2.1.4
  pub_updater: ^0.3.1
  pubspec2: ^1.0.0
  scope: ^4.1.0
  yaml: ^3.1.2
  dart_console: ^1.2.0
  tint: ^2.0.1
  stack_trace: ^1.11.1

dev_dependencies:
  cli_pkg: ^2.4.7
  grinder: ^0.9.4
  test: ^1.24.4
  lints: ^2.1.1
