# This is a basic workflow that is manually triggered

name: Homebrew Deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy Homebrew
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.HOMEBREW_FVM_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Dart
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: stable

      - run: dart pub get

      - run: dart pub run build_runner build --delete-conflicting-outputs

      - run: dart pub run test

      - name: Update Homebrew
        run: dart pub run grinder pkg-homebrew-update
