# This is a basic workflow that is manually triggered

name: Homebrew Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  release:
    types: [published, released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy Homebrew
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.HOMEBREW_FVM_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v1
      - name: Setup Dart
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        uses: ./.github/workflows/common-tests.yml

      - name: Deploy to Homebrew
        run: dart pub run grinder pkg-homebrew-update
