name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/common-tests.yml
  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1.5.0

      - run: dart pub get

      - name: Run tests
        uses: ./.github/workflows/common-tests.yml

      - name: Deploy Github
        run: dart pub run grinder pkg-github-all

      - name: Deploy to Pub
        run: dart pub run grinder pkg-pub-deploy
